
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := AdventureEngine 
# We use the userfunctions.c in System/Backends/Scummvm/ so that we don't
# clutter up the generic one
LOCAL_SRC_FILES := System/Core/agenda.c \
					System/Core/analysis.c \
					System/Core/argacces.c \
					System/Core/bload.c \
					System/Core/bmathfun.c \
					System/Core/bsave.c \
					System/Core/classcom.c \
					System/Core/classexm.c \
					System/Core/classfun.c \
					System/Core/classinf.c \
					System/Core/classini.c \
					System/Core/classpsr.c \
					System/Core/clsltpsr.c \
					System/Core/commline.c \
					System/Core/conscomp.c \
					System/Core/constrct.c \
					System/Core/constrnt.c \
					System/Core/crstrtgy.c \
					System/Core/cstrcbin.c \
					System/Core/cstrccom.c \
					System/Core/cstrcpsr.c \
					System/Core/cstrnbin.c \
					System/Core/cstrnchk.c \
					System/Core/cstrncmp.c \
					System/Core/cstrnops.c \
					System/Core/cstrnpsr.c \
					System/Core/cstrnutl.c \
					System/Core/default.c \
					System/Core/defins.c \
					System/Core/developr.c \
					System/Core/dffctbin.c \
					System/Core/dffctbsc.c \
					System/Core/dffctcmp.c \
					System/Core/dffctdef.c \
					System/Core/dffctpsr.c \
					System/Core/dffnxbin.c \
					System/Core/dffnxcmp.c \
					System/Core/dffnxexe.c \
					System/Core/dffnxfun.c \
					System/Core/dffnxpsr.c \
					System/Core/dfinsbin.c \
					System/Core/dfinscmp.c \
					System/Core/drive.c \
					System/Core/emathfun.c \
					System/Core/engine.c \
					System/Core/envrnmnt.c \
					System/Core/evaluatn.c \
					System/Core/expressn.c \
					System/Core/exprnbin.c \
					System/Core/exprnops.c \
					System/Core/exprnpsr.c \
					System/Core/extnfunc.c \
					System/Core/factbin.c \
					System/Core/factbld.c \
					System/Core/factcmp.c \
					System/Core/factcom.c \
					System/Core/factfun.c \
					System/Core/factgen.c \
					System/Core/facthsh.c \
					System/Core/factlhs.c \
					System/Core/factmch.c \
					System/Core/factmngr.c \
					System/Core/factprt.c \
					System/Core/factqpsr.c \
					System/Core/factqury.c \
					System/Core/factrete.c \
					System/Core/factrhs.c \
					System/Core/filecom.c \
					System/Core/filertr.c \
					System/Core/generate.c \
					System/Core/genrcbin.c \
					System/Core/genrccmp.c \
					System/Core/genrccom.c \
					System/Core/genrcexe.c \
					System/Core/genrcfun.c \
					System/Core/genrcpsr.c \
					System/Core/globlbin.c \
					System/Core/globlbsc.c \
					System/Core/globlcmp.c \
					System/Core/globlcom.c \
					System/Core/globldef.c \
					System/Core/globlpsr.c \
					System/Core/immthpsr.c \
					System/Core/incrrset.c \
					System/Core/inherpsr.c \
					System/Core/inscom.c \
					System/Core/insfile.c \
					System/Core/insfun.c \
					System/Core/insmngr.c \
					System/Core/insmoddp.c \
					System/Core/insmult.c \
					System/Core/inspsr.c \
					System/Core/insquery.c \
					System/Core/insqypsr.c \
					System/Core/iofun.c \
					System/Core/lgcldpnd.c \
					System/Core/memalloc.c \
					System/Core/miscfun.c \
					System/Core/modulbin.c \
					System/Core/modulbsc.c \
					System/Core/modulcmp.c \
					System/Core/moduldef.c \
					System/Core/modulpsr.c \
					System/Core/modulutl.c \
					System/Core/msgcom.c \
					System/Core/msgfun.c \
					System/Core/msgpass.c \
					System/Core/msgpsr.c \
					System/Core/multifld.c \
					System/Core/multifun.c \
					System/Core/objbin.c \
					System/Core/objcmp.c \
					System/Core/objrtbin.c \
					System/Core/objrtbld.c \
					System/Core/objrtcmp.c \
					System/Core/objrtfnx.c \
					System/Core/objrtgen.c \
					System/Core/objrtmch.c \
					System/Core/parsefun.c \
					System/Core/pattern.c \
					System/Core/pprint.c \
					System/Core/prccode.c \
					System/Core/prcdrfun.c \
					System/Core/prcdrpsr.c \
					System/Core/prdctfun.c \
					System/Core/prntutil.c \
					System/Core/proflfun.c \
					System/Core/reorder.c \
					System/Core/reteutil.c \
					System/Core/retract.c \
					System/Core/router.c \
					System/Core/rulebin.c \
					System/Core/rulebld.c \
					System/Core/rulebsc.c \
					System/Core/rulecmp.c \
					System/Core/rulecom.c \
					System/Core/rulecstr.c \
					System/Core/ruledef.c \
					System/Core/ruledlt.c \
					System/Core/rulelhs.c \
					System/Core/rulepsr.c \
					System/Core/scanner.c \
					System/Core/sortfun.c \
					System/Core/strngfun.c \
					System/Core/strngrtr.c \
					System/Core/symblbin.c \
					System/Core/symblcmp.c \
					System/Core/symbol.c \
					System/Core/sysdep.c \
					System/Core/textpro.c \
					System/Core/tmpltbin.c \
					System/Core/tmpltbsc.c \
					System/Core/tmpltcmp.c \
					System/Core/tmpltdef.c \
					System/Core/tmpltfun.c \
					System/Core/tmpltlhs.c \
					System/Core/tmpltpsr.c \
					System/Core/tmpltrhs.c \
					System/Core/tmpltutl.c \
					System/Core/userdata.c \
					System/Core/utility.c \
					System/Core/watch.c \
					System/Core/binary_operations.c \
					System/Initialization/AdventureEngineInit.c \
					System/Platform/ArchitectureDetection.c \
					System/Platform/OSDetection.c \
					System/Platform/HardwareDetection.c \
					System/Platform/Platform.c \
					System/Input/MouseInput.c \
					System/Input/KeyboardInput.c \
					System/Input/Input.c \
					System/System.c \
					System/Core/userfunctions.c \
					System/Backends/Generic/KeyboardImplementation.c \
					System/Backends/Generic/MouseImplementation.c \
					System/Core/Java/clips_Environment.c

LOCAL_C_INCLUDES += $(LOCAL_PATH)

include $(BUILD_SHARED_LIBRARY)
