/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clips_Environment */

#ifndef _Included_clips_Environment
#define _Included_clips_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clips_Environment
 * Method:    getCLIPSVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_clips_Environment_getCLIPSVersion
  (JNIEnv *, jclass);

/*
 * Class:     clips_Environment
 * Method:    createEnvironment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_clips_Environment_createEnvironment
  (JNIEnv *, jobject);

/*
 * Class:     clips_Environment
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    load
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_load
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    loadFacts
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_loadFacts
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    watch
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_watch
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    unwatch
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_unwatch
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    run
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_clips_Environment_run
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    eval
 * Signature: (JLjava/lang/String;)Lclips/PrimitiveValue;
 */
JNIEXPORT jobject JNICALL Java_clips_Environment_eval
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    build
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_build
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    assertString
 * Signature: (JLjava/lang/String;)Lclips/FactAddressValue;
 */
JNIEXPORT jobject JNICALL Java_clips_Environment_assertString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    factIndex
 * Signature: (Lclips/Environment;JJ)J
 */
JNIEXPORT jlong JNICALL Java_clips_Environment_factIndex
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    getFactSlot
 * Signature: (Lclips/Environment;JJLjava/lang/String;)Lclips/PrimitiveValue;
 */
JNIEXPORT jobject JNICALL Java_clips_Environment_getFactSlot
  (JNIEnv *, jclass, jobject, jlong, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    makeInstance
 * Signature: (JLjava/lang/String;)Lclips/InstanceAddressValue;
 */
JNIEXPORT jobject JNICALL Java_clips_Environment_makeInstance
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    getInstanceName
 * Signature: (Lclips/Environment;JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_clips_Environment_getInstanceName
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    directGetSlot
 * Signature: (Lclips/Environment;JJLjava/lang/String;)Lclips/PrimitiveValue;
 */
JNIEXPORT jobject JNICALL Java_clips_Environment_directGetSlot
  (JNIEnv *, jclass, jobject, jlong, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    destroyEnvironment
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_destroyEnvironment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    commandLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_commandLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    getInputBuffer
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_clips_Environment_getInputBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    setInputBuffer
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_setInputBuffer
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    getInputBufferCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_clips_Environment_getInputBufferCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    setInputBufferCount
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_clips_Environment_setInputBufferCount
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    expandInputBuffer
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_expandInputBuffer
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     clips_Environment
 * Method:    appendInputBuffer
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_appendInputBuffer
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     clips_Environment
 * Method:    inputBufferContainsCommand
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_inputBufferContainsCommand
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    commandLoopOnceThenBatch
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_commandLoopOnceThenBatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    printBanner
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_printBanner
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    printPrompt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_printPrompt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     clips_Environment
 * Method:    addRouter
 * Signature: (JLjava/lang/String;ILclips/Router;)Z
 */
JNIEXPORT jboolean JNICALL Java_clips_Environment_addRouter
  (JNIEnv *, jobject, jlong, jstring, jint, jobject);

/*
 * Class:     clips_Environment
 * Method:    incrementFactCount
 * Signature: (Lclips/Environment;JJ)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_incrementFactCount
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    decrementFactCount
 * Signature: (Lclips/Environment;JJ)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_decrementFactCount
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    incrementInstanceCount
 * Signature: (Lclips/Environment;JJ)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_incrementInstanceCount
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     clips_Environment
 * Method:    decrementInstanceCount
 * Signature: (Lclips/Environment;JJ)V
 */
JNIEXPORT void JNICALL Java_clips_Environment_decrementInstanceCount
  (JNIEnv *, jobject, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
